/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team.java.GUI;

/**
 *
 * @author ngoc canh;
 */
public class Hoadon extends javax.swing.JFrame {

    /**
     * Creates new form Hoadon
     */
    public Hoadon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        txtMaNV1 = new javax.swing.JTextField();
        txtMaKH = new javax.swing.JTextField();
        txtTongTien1 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel93 = new javax.swing.JLabel();
        comTimKiem1 = new javax.swing.JComboBox<>();
        jSeparator13 = new javax.swing.JSeparator();
        txtTimKiem3 = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        btnThemHD = new javax.swing.JButton();
        btnSuaHD = new javax.swing.JButton();
        btnXoaHD = new javax.swing.JButton();
        btnLamMoiHD = new javax.swing.JButton();
        btnInHD = new javax.swing.JButton();
        btnCTHD = new javax.swing.JButton();
        btnRSNXB1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setLayout(null);

        tblHoaDon.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã nhân viên", "Mã khách hàng", "Ngày lập", "Tổng tiền"
            }
        ));
        tblHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblHoaDon.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(tblHoaDon);

        jPanel10.add(jScrollPane3);
        jScrollPane3.setBounds(380, 60, 530, 450);

        jPanel16.setBackground(new java.awt.Color(204, 255, 204));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Mã hóa đơn");
        jLabel12.setPreferredSize(new java.awt.Dimension(1000, 20));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Mã nhân viên");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Mã khách hàng");
        jLabel19.setPreferredSize(new java.awt.Dimension(1000, 20));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("Ngày lập");
        jLabel20.setPreferredSize(new java.awt.Dimension(1000, 20));

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setText("Tổng tiền (VNĐ)");
        jLabel21.setPreferredSize(new java.awt.Dimension(1000, 20));

        txtMaHD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtMaNV1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtMaKH.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtTongTien1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(txtTongTien1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaNV1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtMaNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel16);
        jPanel16.setBounds(20, 130, 320, 240);
        jPanel10.add(jLabel93);
        jLabel93.setBounds(310, 70, 40, 30);

        comTimKiem1.setBackground(new java.awt.Color(204, 204, 204));
        comTimKiem1.setEditable(true);
        comTimKiem1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tìm kiếm theo mã hóa đơn", "Tìm kiếm theo mã nhân viên", "Tìm kiếm theo ngày lập" }));
        comTimKiem1.setBorder(null);
        comTimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comTimKiem1ActionPerformed(evt);
            }
        });
        jPanel10.add(comTimKiem1);
        comTimKiem1.setBounds(60, 40, 240, 30);

        jSeparator13.setForeground(new java.awt.Color(0, 153, 255));
        jPanel10.add(jSeparator13);
        jSeparator13.setBounds(60, 100, 240, 10);

        txtTimKiem3.setBackground(new java.awt.Color(204, 255, 204));
        txtTimKiem3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTimKiem3.setBorder(null);
        txtTimKiem3.setOpaque(false);
        txtTimKiem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiem3ActionPerformed(evt);
            }
        });
        jPanel10.add(txtTimKiem3);
        txtTimKiem3.setBounds(60, 70, 240, 30);

        btnThemHD.setBackground(new java.awt.Color(0, 204, 204));
        btnThemHD.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnThemHD.setForeground(new java.awt.Color(0, 51, 153));
        btnThemHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_add_30px_1.png"))); // NOI18N
        btnThemHD.setText("THÊM");
        btnThemHD.setBorder(null);
        btnThemHD.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThemHD.setPreferredSize(new java.awt.Dimension(80, 40));
        btnThemHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHDActionPerformed(evt);
            }
        });
        jPanel27.add(btnThemHD);

        btnSuaHD.setBackground(new java.awt.Color(0, 204, 204));
        btnSuaHD.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSuaHD.setForeground(new java.awt.Color(0, 51, 153));
        btnSuaHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_settings_30px.png"))); // NOI18N
        btnSuaHD.setText("SỬA");
        btnSuaHD.setBorder(null);
        btnSuaHD.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSuaHD.setPreferredSize(new java.awt.Dimension(80, 40));
        jPanel27.add(btnSuaHD);

        btnXoaHD.setBackground(new java.awt.Color(0, 204, 204));
        btnXoaHD.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnXoaHD.setForeground(new java.awt.Color(0, 51, 153));
        btnXoaHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_cancel_30px_9.png"))); // NOI18N
        btnXoaHD.setText("XÓA");
        btnXoaHD.setBorder(null);
        btnXoaHD.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXoaHD.setPreferredSize(new java.awt.Dimension(80, 40));
        jPanel27.add(btnXoaHD);

        btnLamMoiHD.setBackground(new java.awt.Color(0, 204, 204));
        btnLamMoiHD.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLamMoiHD.setForeground(new java.awt.Color(0, 51, 153));
        btnLamMoiHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/available_updates_20px.png"))); // NOI18N
        btnLamMoiHD.setText("MỚI");
        btnLamMoiHD.setBorder(null);
        btnLamMoiHD.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLamMoiHD.setPreferredSize(new java.awt.Dimension(80, 40));
        jPanel27.add(btnLamMoiHD);

        btnInHD.setBackground(new java.awt.Color(0, 204, 204));
        btnInHD.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnInHD.setForeground(new java.awt.Color(0, 51, 153));
        btnInHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_printer_20px.png"))); // NOI18N
        btnInHD.setText("IN");
        btnInHD.setBorder(null);
        btnInHD.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnInHD.setPreferredSize(new java.awt.Dimension(80, 40));
        jPanel27.add(btnInHD);

        btnCTHD.setBackground(new java.awt.Color(0, 204, 204));
        btnCTHD.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCTHD.setForeground(new java.awt.Color(0, 51, 153));
        btnCTHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-details-20.png"))); // NOI18N
        btnCTHD.setText("CHI TIẾT");
        btnCTHD.setBorder(null);
        btnCTHD.setPreferredSize(new java.awt.Dimension(80, 40));
        jPanel27.add(btnCTHD);

        jPanel10.add(jPanel27);
        jPanel27.setBounds(30, 390, 290, 120);

        btnRSNXB1.setBackground(new java.awt.Color(102, 153, 255));
        btnRSNXB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/available_updates_26px.png"))); // NOI18N
        btnRSNXB1.setBorder(null);
        jPanel10.add(btnRSNXB1);
        btnRSNXB1.setBounds(860, 20, 43, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comTimKiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comTimKiem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comTimKiem1ActionPerformed

    private void txtTimKiem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiem3ActionPerformed

    private void btnThemHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemHDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hoadon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCTHD;
    private javax.swing.JButton btnInHD;
    private javax.swing.JButton btnLamMoiHD;
    private javax.swing.JButton btnRSNXB1;
    private javax.swing.JButton btnSuaHD;
    private javax.swing.JButton btnThemHD;
    private javax.swing.JButton btnXoaHD;
    private javax.swing.JComboBox<String> comTimKiem1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaNV1;
    private javax.swing.JTextField txtTimKiem3;
    private javax.swing.JTextField txtTongTien1;
    // End of variables declaration//GEN-END:variables
}
