/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team.java.GUI;

import com.toedter.calendar.JTextFieldDateEditor;

/**
 *
 * @author ngoc canh;
 */
public class NhapSach extends javax.swing.JFrame {

    /**
     * Creates new form NhapSach
     */
    public NhapSach() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        tblPhieuNhap = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        txtMaPhieuNhap1 = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        txtMaNCC1 = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        dateNgayNhap = new com.toedter.calendar.JDateChooser();
        jLabel80 = new javax.swing.JLabel();
        comTimKiem = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        txtTimKiem11 = new javax.swing.JTextField();
        jLabel90 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        btnThemPN = new javax.swing.JButton();
        btnSuaPN = new javax.swing.JButton();
        btnXoaPN = new javax.swing.JButton();
        btnLamMoiPN = new javax.swing.JButton();
        btnInPN = new javax.swing.JButton();
        btnCTPN = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(null);

        tblPhieuNhap.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        tblPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu nhập", "Mã nhân viên", "Mã nhà cung cấp", "Ngày nhập", "Tổng tiền"
            }
        ));
        tblPhieuNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblPhieuNhap.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tblPhieuNhap.getTableHeader().setResizingAllowed(false);
        tblPhieuNhap.getTableHeader().setReorderingAllowed(false);
        jScrollPane13.setViewportView(tblPhieuNhap);

        jPanel2.add(jScrollPane13);
        jScrollPane13.setBounds(370, 50, 530, 450);

        jPanel13.setBackground(new java.awt.Color(204, 255, 204));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setText("Mã phiếu nhập");
        jLabel27.setPreferredSize(new java.awt.Dimension(1000, 20));

        jLabel57.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel57.setText("Mã nhân viên");

        jLabel60.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel60.setText("Mã NCC");
        jLabel60.setPreferredSize(new java.awt.Dimension(1000, 20));

        jLabel61.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel61.setText("Ngày nhập");
        jLabel61.setPreferredSize(new java.awt.Dimension(1000, 20));

        jLabel62.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel62.setText("Tổng tiền (VNĐ)");
        jLabel62.setPreferredSize(new java.awt.Dimension(1000, 20));

        txtMaPhieuNhap1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtMaPhieuNhap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaPhieuNhap1ActionPerformed(evt);
            }
        });

        txtMaNV.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtMaNCC1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtTongTien.setEditable(false);
        txtTongTien.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        dateNgayNhap.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaNCC1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaPhieuNhap1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateNgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaPhieuNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNCC1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        JTextFieldDateEditor editor5 = (JTextFieldDateEditor) dateNgayNhap.getDateEditor();
        editor5.setEditable(false);

        jPanel2.add(jPanel13);
        jPanel13.setBounds(20, 130, 320, 250);
        jPanel2.add(jLabel80);
        jLabel80.setBounds(310, 70, 40, 30);

        comTimKiem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tìm kiếm theo mã phiếu nhập", "Tìm kiếm theo mã nhân viên", "Tìm kiếm theo ngày nhập" }));
        comTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comTimKiemActionPerformed(evt);
            }
        });
        jPanel2.add(comTimKiem);
        comTimKiem.setBounds(60, 40, 240, 30);

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(60, 100, 240, 10);

        txtTimKiem11.setBackground(new java.awt.Color(204, 255, 204));
        txtTimKiem11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTimKiem11.setBorder(null);
        txtTimKiem11.setOpaque(false);
        txtTimKiem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiem11ActionPerformed(evt);
            }
        });
        jPanel2.add(txtTimKiem11);
        txtTimKiem11.setBounds(60, 70, 240, 30);

        jLabel90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_search_20px_1.png"))); // NOI18N
        jPanel2.add(jLabel90);
        jLabel90.setBounds(310, 70, 30, 40);

        jPanel34.setBackground(new java.awt.Color(204, 255, 204));

        btnThemPN.setBackground(new java.awt.Color(0, 204, 204));
        btnThemPN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnThemPN.setForeground(new java.awt.Color(0, 51, 153));
        btnThemPN.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\AppQuanLyCuaHangSach\\src\\Image\\icons8_add_30px_1.png")); // NOI18N
        btnThemPN.setText("THÊM");
        btnThemPN.setBorder(null);
        btnThemPN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThemPN.setPreferredSize(new java.awt.Dimension(80, 40));
        btnThemPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPNActionPerformed(evt);
            }
        });
        jPanel34.add(btnThemPN);

        btnSuaPN.setBackground(new java.awt.Color(0, 204, 204));
        btnSuaPN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSuaPN.setForeground(new java.awt.Color(0, 51, 153));
        btnSuaPN.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\AppQuanLyCuaHangSach\\src\\Image\\icons8_settings_30px.png")); // NOI18N
        btnSuaPN.setText("SỬA");
        btnSuaPN.setBorder(null);
        btnSuaPN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSuaPN.setPreferredSize(new java.awt.Dimension(80, 40));
        jPanel34.add(btnSuaPN);

        btnXoaPN.setBackground(new java.awt.Color(0, 204, 204));
        btnXoaPN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnXoaPN.setForeground(new java.awt.Color(0, 51, 153));
        btnXoaPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_cancel_30px_9.png"))); // NOI18N
        btnXoaPN.setText("XÓA");
        btnXoaPN.setBorder(null);
        btnXoaPN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXoaPN.setPreferredSize(new java.awt.Dimension(80, 40));
        jPanel34.add(btnXoaPN);

        btnLamMoiPN.setBackground(new java.awt.Color(0, 204, 204));
        btnLamMoiPN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLamMoiPN.setForeground(new java.awt.Color(0, 51, 153));
        btnLamMoiPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/available_updates_20px.png"))); // NOI18N
        btnLamMoiPN.setText("MỚI");
        btnLamMoiPN.setBorder(null);
        btnLamMoiPN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLamMoiPN.setPreferredSize(new java.awt.Dimension(80, 40));
        jPanel34.add(btnLamMoiPN);

        btnInPN.setBackground(new java.awt.Color(0, 204, 204));
        btnInPN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnInPN.setForeground(new java.awt.Color(0, 51, 153));
        btnInPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_printer_20px.png"))); // NOI18N
        btnInPN.setText("IN");
        btnInPN.setBorder(null);
        btnInPN.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnInPN.setPreferredSize(new java.awt.Dimension(80, 40));
        jPanel34.add(btnInPN);

        btnCTPN.setBackground(new java.awt.Color(0, 204, 204));
        btnCTPN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCTPN.setForeground(new java.awt.Color(0, 51, 153));
        btnCTPN.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Documents\\NetBeansProjects\\AppQuanLyCuaHangSach\\src\\Image\\more_details_20px.png")); // NOI18N
        btnCTPN.setText("CHI TIẾT");
        btnCTPN.setBorder(null);
        btnCTPN.setPreferredSize(new java.awt.Dimension(80, 40));
        jPanel34.add(btnCTPN);

        jPanel2.add(jPanel34);
        jPanel34.setBounds(20, 380, 290, 90);

        jButton9.setBackground(new java.awt.Color(102, 153, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/available_updates_26px.png"))); // NOI18N
        jButton9.setBorder(null);
        jPanel2.add(jButton9);
        jButton9.setBounds(850, 10, 43, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 975, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaPhieuNhap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaPhieuNhap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaPhieuNhap1ActionPerformed

    private void comTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comTimKiemActionPerformed

    private void txtTimKiem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiem11ActionPerformed

    private void btnThemPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemPNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCTPN;
    private javax.swing.JButton btnInPN;
    private javax.swing.JButton btnLamMoiPN;
    private javax.swing.JButton btnSuaPN;
    private javax.swing.JButton btnThemPN;
    private javax.swing.JButton btnXoaPN;
    private javax.swing.JComboBox<String> comTimKiem;
    private com.toedter.calendar.JDateChooser dateNgayNhap;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tblPhieuNhap;
    private javax.swing.JTextField txtMaNCC1;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaPhieuNhap1;
    private javax.swing.JTextField txtTimKiem11;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
